# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentProvider_Server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ontentProvider_Server.proto\"<\n\x13TransmitFileRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\t\".\n\x14TransmitFileResponse\x12\x16\n\x0etransmitStatus\x18\x01 \x01(\t\"\"\n\x0eGetFileRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"8\n\x0fGetFileResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\t\"\'\n\x0fsyncFileRequest\x12\x14\n\x0c\x66ileNameList\x18\x01 \x03(\t\"(\n\x10syncFileResponse\x12\x14\n\x0c\x66ileNameList\x18\x01 \x03(\t\"<\n\x15serverToServerRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\"?\n\x16serverToServerResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileContent\x18\x02 \x01(\t2\x82\x02\n\x16\x43ontentProvider_Server\x12;\n\x0cTransmitFile\x12\x14.TransmitFileRequest\x1a\x15.TransmitFileResponse\x12,\n\x07GetFile\x12\x0f.GetFileRequest\x1a\x10.GetFileResponse\x12\x34\n\rreplicateFile\x12\x10.syncFileRequest\x1a\x11.syncFileResponse\x12G\n\x14HandleForwardRequest\x12\x16.serverToServerRequest\x1a\x17.serverToServerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentProvider_Server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRANSMITFILEREQUEST']._serialized_start=32
  _globals['_TRANSMITFILEREQUEST']._serialized_end=92
  _globals['_TRANSMITFILERESPONSE']._serialized_start=94
  _globals['_TRANSMITFILERESPONSE']._serialized_end=140
  _globals['_GETFILEREQUEST']._serialized_start=142
  _globals['_GETFILEREQUEST']._serialized_end=176
  _globals['_GETFILERESPONSE']._serialized_start=178
  _globals['_GETFILERESPONSE']._serialized_end=234
  _globals['_SYNCFILEREQUEST']._serialized_start=236
  _globals['_SYNCFILEREQUEST']._serialized_end=275
  _globals['_SYNCFILERESPONSE']._serialized_start=277
  _globals['_SYNCFILERESPONSE']._serialized_end=317
  _globals['_SERVERTOSERVERREQUEST']._serialized_start=319
  _globals['_SERVERTOSERVERREQUEST']._serialized_end=379
  _globals['_SERVERTOSERVERRESPONSE']._serialized_start=381
  _globals['_SERVERTOSERVERRESPONSE']._serialized_end=444
  _globals['_CONTENTPROVIDER_SERVER']._serialized_start=447
  _globals['_CONTENTPROVIDER_SERVER']._serialized_end=705
# @@protoc_insertion_point(module_scope)
