# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ContentProvider_Server_pb2 as ContentProvider__Server__pb2


class ContentProvider_ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TransmitFile = channel.unary_unary(
                '/ContentProvider_Server/TransmitFile',
                request_serializer=ContentProvider__Server__pb2.TransmitFileRequest.SerializeToString,
                response_deserializer=ContentProvider__Server__pb2.TransmitFileResponse.FromString,
                )
        self.GetFile = channel.unary_unary(
                '/ContentProvider_Server/GetFile',
                request_serializer=ContentProvider__Server__pb2.GetFileRequest.SerializeToString,
                response_deserializer=ContentProvider__Server__pb2.GetFileResponse.FromString,
                )
        self.replicateFile = channel.unary_unary(
                '/ContentProvider_Server/replicateFile',
                request_serializer=ContentProvider__Server__pb2.syncFileRequest.SerializeToString,
                response_deserializer=ContentProvider__Server__pb2.syncFileResponse.FromString,
                )
        self.HandleForwardRequest = channel.unary_unary(
                '/ContentProvider_Server/HandleForwardRequest',
                request_serializer=ContentProvider__Server__pb2.serverToServerRequest.SerializeToString,
                response_deserializer=ContentProvider__Server__pb2.serverToServerResponse.FromString,
                )


class ContentProvider_ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TransmitFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def replicateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HandleForwardRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentProvider_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TransmitFile': grpc.unary_unary_rpc_method_handler(
                    servicer.TransmitFile,
                    request_deserializer=ContentProvider__Server__pb2.TransmitFileRequest.FromString,
                    response_serializer=ContentProvider__Server__pb2.TransmitFileResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=ContentProvider__Server__pb2.GetFileRequest.FromString,
                    response_serializer=ContentProvider__Server__pb2.GetFileResponse.SerializeToString,
            ),
            'replicateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.replicateFile,
                    request_deserializer=ContentProvider__Server__pb2.syncFileRequest.FromString,
                    response_serializer=ContentProvider__Server__pb2.syncFileResponse.SerializeToString,
            ),
            'HandleForwardRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleForwardRequest,
                    request_deserializer=ContentProvider__Server__pb2.serverToServerRequest.FromString,
                    response_serializer=ContentProvider__Server__pb2.serverToServerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ContentProvider_Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentProvider_Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TransmitFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContentProvider_Server/TransmitFile',
            ContentProvider__Server__pb2.TransmitFileRequest.SerializeToString,
            ContentProvider__Server__pb2.TransmitFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContentProvider_Server/GetFile',
            ContentProvider__Server__pb2.GetFileRequest.SerializeToString,
            ContentProvider__Server__pb2.GetFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def replicateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContentProvider_Server/replicateFile',
            ContentProvider__Server__pb2.syncFileRequest.SerializeToString,
            ContentProvider__Server__pb2.syncFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HandleForwardRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ContentProvider_Server/HandleForwardRequest',
            ContentProvider__Server__pb2.serverToServerRequest.SerializeToString,
            ContentProvider__Server__pb2.serverToServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
